### ISSUE TITLE
Not working! 

### ISSUE THREAD

**Issue by HardikJain02** [iamvatsalpatel/RoomPlan-iOS-App#1]
when i click over "start scan" it shows me blank screen.

![image](https://github.com/user-attachments/assets/c5de0822-3063-4a9a-a317-09de309a11fd)

![image](https://github.com/user-attachments/assets/9f6076e3-845a-453e-92f8-175520ead891)

**Comment by iamvatsalpatel** [comment]
Which iPhone model and iOS version are you using?

**Comment by HardikJain02** [comment]
SE 2nd Generation and iOS 17.6.1

**Comment by iamvatsalpatel** [comment]
The absence of a LiDAR sensor might be causing an issue. However, the app is functioning properly on the iPhone 14 Pro Max running iOS 18.1.1.

![IMG_1785](https://github.com/user-attachments/assets/0636c6dc-ef62-4f24-8ba9-7e8ece12ce93)
![IMG_1789](https://github.com/user-attachments/assets/5607dfa5-de49-4b01-8da7-aadb9b29fa15)

**Comment by HardikJain02** [comment]
thanks, I'll check with another iphone which has lidar. (silly me)
